# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Build a new production version (apk, signed)"
  lane :apk do
    gradle(task: "clean")
    gradle(
    task: 'assemble',
    build_type: 'Release')
  end

  desc "Build a new production version (bundle, signed)"
  lane :bundle do
    gradle(task: "clean")
    gradle(
      task: 'bundle',
      build_type: 'Release'
    )
  end

  desc "Build and deploy a new production version to the internal testing track"
  lane :playstore do
    bundle
    upload_to_play_store(track: 'internal')
  end

end
